### Pandas

In [77]:
"""
- Loading & saving data
pd.read_csv()
pd.read_excel()
pd.read_json()

df.to_csv()
df.to_excel()

- Understanding your DataFrame
df.head()
df.tail()
df.shape
df.info()
df.describe()
df.columns
df.dtypes
df.index

- Selecting data
df['column_name']
df[['column1', 'column2']]
df.loc[row_index, 'column_name']

- Filtering data
df[df['column_name'] > value]

- Missing data
df.isna()
df.isnull()
df.notna()
df.dropna()
df.fillna()

- Grouping and aggregation
df.groupby('column_name').mean()
df.groupby('column_name').sum()
df.groupby('column_name').agg({'column1': 'mean', 'column2': 'sum'})

- Sorting data
df.sort_values(by='column_name', ascending=True)
df.sort_index()

- Statistical operations
df["column_name"].mean()
df["column_name"].median()
df["column_name"].mode()
df["column_name"].min()
df["column_name"].max()
df["column_name"].sum()
df["column_name"].std()
df["column_name"].count()

- Unique values
df["column_name"].unique()
df["column_name"].nunique()
df["column_name"].value_counts()

-string operations
df["column_name"].str.lower()
df["column_name"].str.upper()
df["column_name"].str.strip()
df["column_name"].str.replace("old", "new")
df["column_name"].str.replace(r"regex_pattern", "replacement", regex=True)
df["column_name"].str.contains("substring")
df["column_name"].str.startswith("prefix")
df["column_name"].str.endswith("suffix")
df["column_name"].str.split("delimiter")
df["column_name"].str.len()
df["column_name"].str.get(index)
df["column_name"].str.slice(start, end)
df["column_name"].str.extract(r"regex_pattern")
df["column_name"].str.findall(r"regex_pattern")
df["column_name"].str.join("delimiter")
df["column_name"].str.cat(df["other_column"], sep="delimiter")

- Creating / modifying columns
df['new_column'] = df['column1'] + df['column2']
df['new_column'] = df['column_name'].apply(lambda x: x * 2)
df["column_name"] = df["column_name"].fillna(df["column_name"].mean())

- duplicates
df.duplicated()
df.drop_duplicates()

"""

'\n- Loading & saving data\npd.read_csv()\npd.read_excel()\npd.read_json()\n\ndf.to_csv()\ndf.to_excel()\n\n- Understanding your DataFrame\ndf.head()\ndf.tail()\ndf.shape\ndf.info()\ndf.describe()\ndf.columns\ndf.dtypes\ndf.index\n\n- Selecting data\ndf[\'column_name\']\ndf[[\'column1\', \'column2\']]\ndf.loc[row_index, \'column_name\']\n\n- Filtering data\ndf[df[\'column_name\'] > value]\n\n- Missing data\ndf.isna()\ndf.isnull()\ndf.notna()\ndf.dropna()\ndf.fillna()\n\n- Grouping and aggregation\ndf.groupby(\'column_name\').mean()\ndf.groupby(\'column_name\').sum()\ndf.groupby(\'column_name\').agg({\'column1\': \'mean\', \'column2\': \'sum\'})\n\n- Sorting data\ndf.sort_values(by=\'column_name\', ascending=True)\ndf.sort_index()\n\n- Statistical operations\ndf["column_name"].mean()\ndf["column_name"].median()\ndf["column_name"].mode()\ndf["column_name"].min()\ndf["column_name"].max()\ndf["column_name"].sum()\ndf["column_name"].std()\ndf["column_name"].count()\n\n- Unique values\ndf["column_name"].unique()\ndf["column_name"].nunique()\ndf["column_name"].value_counts()\n\n-string operations\ndf["column_name"].str.lower()\ndf["column_name"].str.upper()\ndf["column_name"].str.strip()\ndf["column_name"].str.replace("old", "new")\ndf["column_name"].str.replace(r"regex_pattern", "replacement", regex=True)\ndf["column_name"].str.contains("substring")\ndf["column_name"].str.startswith("prefix")\ndf["column_name"].str.endswith("suffix")\ndf["column_name"].str.split("delimiter")\ndf["column_name"].str.len()\ndf["column_name"].str.get(index)\ndf["column_name"].str.slice(start, end)\ndf["column_name"].str.extract(r"regex_pattern")\ndf["column_name"].str.findall(r"regex_pattern")\ndf["column_name"].str.join("delimiter")\ndf["column_name"].str.cat(df["other_column"], sep="delimiter")\n\n- Creating / modifying columns\ndf[\'new_column\'] = df[\'column1\'] + df[\'column2\']\ndf[\'new_column\'] = df[\'column_name\'].apply(lambda x: x * 2)\ndf["column_name"] = df["column_name"].fillna(df["column_name"].mean())\n\n- duplicates\ndf.duplicated()\ndf.drop_duplicates()\n\n'

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\suruthi ravikumar\desktop\datascience\venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\suruthi ravikumar\desktop\datascience\venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\suruthi ravikumar\desktop\datascience\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\suruthi ravikumar\desktop\datascience\venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\suruthi ravikumar\desktop\datascience\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
pip install openpyxl #work with Excel files in Python. It is a library that allows you to read and write Excel files in the .xlsx format.

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#work'

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [48]:
my_data = {
    'car' :["BMW", "Volvo", "Ford"],
    'price' :[50000, 60000, 40000]
}
a=pd.DataFrame(my_data)
print(a)

     car  price
0    BMW  50000
1  Volvo  60000
2   Ford  40000

In [22]:
titanic_df = pd.read_csv('train_titanic.csv')

In [5]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
titanic_df.dtypes # gives the data type of each column in the DataFrame

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [49]:
titanic_df.info() # provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [50]:
titanic_df.columns # returns the column labels of the DataFrame as an Index object

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [19]:
titanic_df.to_excel('titanic_data.xlsx', sheet_name='titanic_data', index=False) # Save the DataFrame to an Excel file without the index column

In [20]:
titanic_df= pd.read_excel('titanic_data.xlsx', sheet_name='titanic_data') # Read the Excel file into a DataFrame

In [23]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [24]:
age = titanic_df['Age'] # Access the 'Age' column of the DataFrame

In [25]:
age.head() # Display the first few values of the 'Age' column

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [26]:
type(titanic_df['Age']) # Check the type of the 'Age' column

pandas.Series

In [30]:
titanic_df['Age'].shape # Get the shape of the 'Age' column

(891,)

In [27]:
age_sex = titanic_df[['Age', 'Sex']] # Access the 'Age' and 'Sex' columns of the DataFrame

In [29]:
age_sex.head() # Display the first few rows of the 'Age' and 'Sex' columns

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [31]:
titanic_df[['Age', 'Sex']].shape

(891, 2)

In [32]:
age_above_30 = titanic_df[titanic_df['Age'] > 30] # Filter the DataFrame to include only rows where 'Age' is greater than 30
age_above_30.head() # Display the first few rows of the filtered DataFrame

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [34]:
class_2_and_3 = titanic_df[titanic_df['Pclass'].isin([2, 3])] # Filter the DataFrame to include only rows where 'Pclass' is either 2 or 3
#class_2_and_3 = titanic_df[(titanic_df['Pclass'] == 2) | (titanic_df['Pclass'] == 3)] # Alternative way to filter the DataFrame for 'Pclass' 2 or 3
class_2_and_3.head() # Display the first few rows of the filtered DataFrame

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [35]:
age_no_na = titanic_df['Age'].notna() # Create a boolean Series indicating which values in the 'Age' column are not NaN 
age_no_na.head() # Display the first few values of the boolean Series

0    True
1    True
2    True
3    True
4    True
Name: Age, dtype: bool

In [36]:
age_no_na = titanic_df[titanic_df['Age'].notna()] # Filter the DataFrame to include only rows where 'Age' is not NaN
age_no_na.head() # Display the first few values of the boolean Series

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
adult_names = titanic_df.loc[titanic_df['Age'] >= 18, 'Name'] # Use .loc to filter the DataFrame for rows where 'Age' is greater than or equal to 18 and select the 'Name' column
adult_names.head() # Display the first few names of adults

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [38]:
adult_names = titanic_df.loc[titanic_df['Age'] >= 18] # Use .loc to filter the DataFrame for rows where 'Age' is greater than or equal to 18
adult_names.head() # Display the first few names of adults

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
titanic_df.iloc[0:5, 0:3] # Use .iloc to select the first 5 rows and the first 3 columns of the DataFrame

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [40]:
titanic_df["Age"].mean() # Calculate the mean of all numeric columns in the DataFrame

29.69911764705882

In [41]:
titanic_df["Age"].median() # Calculate the median of the 'Age' column in the DataFrame

28.0

In [43]:
titanic_df[["Age", "Fare"]].median() # Calculate the median of the 'Age' column in the DataFrame

Age     28.0000
Fare    14.4542
dtype: float64

In [45]:
titanic_df[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [46]:
titanic_df[['Age', 'Sex']].groupby('Sex').mean() # Group the DataFrame by 'Sex' and calculate the mean of the 'Age' column for each group

              Age
Sex
female  27.915709
male    30.726645

this script selects sex and age column from the titanic dataframe, group the data by sex column groupby(sex), and calculate mean age for each group (male and female) (sex).mean() #similar to sql groupby

In [51]:
titanic_df["Pclass"].value_counts() # Count the occurrences of each unique value in the 'Pclass' column

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [52]:
titanic_df.groupby('Pclass')['Pclass'].count() # Group the DataFrame by 'Pclass' and count the number of occurrences of each unique value in the 'Pclass' column

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [54]:
#if i want to sort by age 
titanic_df.sort_values(by='Age', ascending=False).head() # Sort the DataFrame by the 'Age' column in descending order and display the first few rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [55]:
titanic_df["name"].str.lower() # Convert the 'name' column to lowercase

KeyError: 'name'

In [56]:
titanic_df["Name"].str.lower() # Convert the 'name' column to lowercase

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [60]:
#split the name column into first and last name
titanic_df[['First_Name', 'Last_Name']] = titanic_df['Name'].str.split(',', n=1, expand=True) # Split the 'Name' column into two new columns 'First_Name' and 'Last_Name' based on the first space character
print(titanic_df[['First_Name', 'Last_Name']].head()) # Display the first few rows of the new 'First_Name' and 'Last_Name' columns

  First_Name                                    Last_Name
0     Braund                              Mr. Owen Harris
1    Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2  Heikkinen                                  Miss. Laina
3   Futrelle           Mrs. Jacques Heath (Lily May Peel)
4      Allen                            Mr. William Henry

In [ ]:
print(titanic_df.head()) # Display the first few rows of the DataFrame - here the new cols will added it in the end of the df

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked First_Name  \
0      0         A/5 21171   7.2500   NaN        S     Braund
1      0          PC 17599  71.2833   C85        C    Cumings
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen
3      0            113803  53.1000  C123        S   Futrelle
4      0            373450   8.0500   NaN        S      Allen

                                     Last_Name
0                              Mr. Owen Harris
1   Mrs. John Bradley (Florence Briggs Thayer)
2                                  Miss. Laina
3           Mrs. Jacques Heath (Lily May Peel)
4                            Mr. William Henry

In [62]:
#to print the exact name contains the word "Braund"
# Filter the DataFrame to include only rows where the 'Name' column contains the substring 'Braund'       
print(titanic_df[titanic_df['Name'].str.contains('Braund')]) # Display the filtered DataFrame

     PassengerId  Survived  Pclass                       Name   Sex   Age  \
0              1         0       3    Braund, Mr. Owen Harris  male  22.0
477          478         0       3  Braund, Mr. Lewis Richard  male  29.0

     SibSp  Parch     Ticket    Fare Cabin Embarked First_Name  \
0        1      0  A/5 21171  7.2500   NaN        S     Braund
477      1      0       3460  7.0458   NaN        S     Braund

              Last_Name
0       Mr. Owen Harris
477   Mr. Lewis Richard

In [63]:
titanic_df["Name"].str.len() # Calculate the length of each string in the 'Name' column

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [65]:
#replace the sex with F and M
titanic_df['Sex'] = titanic_df['Sex'].replace({'female': 'F', 'male': 'M'}) # Replace the values
print(titanic_df['Sex'].head()) # Display the first few rows of the 'Sex' column after

0    M
1    F
2    F
3    F
4    M
Name: Sex, dtype: str

In [74]:
# Find the longest name
#Give me the index/row number where the largest value occurs.
titanic_df['Name'].str.len().idxmax() # Find the index of the longest name in the 'Name' column

307

In [76]:
#locate the row with the longest name
titanic_df.loc[titanic_df['Name'].str.len().idxmax(),"Name"] # Use .loc to access the row with the longest name based on the index obtained from idxmax()

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'